// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: lunarclient/apollo/common/v1/version.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A reference to a specific version (released by Mojang) of Minecraft.
// For example, Minecraft 1.8.9, or 1.19.4
type MinecraftVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The enum encoding of this version. For example, "v1_8_9"
	Enum          string `protobuf:"bytes,1,opt,name=enum,proto3" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinecraftVersion) Reset() {
	*x = MinecraftVersion{}
	mi := &file_lunarclient_apollo_common_v1_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinecraftVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinecraftVersion) ProtoMessage() {}

func (x *MinecraftVersion) ProtoReflect() protoreflect.Message {
	mi := &file_lunarclient_apollo_common_v1_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinecraftVersion.ProtoReflect.Descriptor instead.
func (*MinecraftVersion) Descriptor() ([]byte, []int) {
	return file_lunarclient_apollo_common_v1_version_proto_rawDescGZIP(), []int{0}
}

func (x *MinecraftVersion) GetEnum() string {
	if x != nil {
		return x.Enum
	}
	return ""
}

// A reference to a specific version (released by Moonsworth) of the
// Lunar Client modpack.
type LunarClientVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Git branch this version was based on
	GitBranch string `protobuf:"bytes,1,opt,name=git_branch,json=gitBranch,proto3" json:"git_branch,omitempty"`
	// The Git commit this version was based on
	GitCommit string `protobuf:"bytes,2,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	// The semver encoding of this version. For example, "2.5.1"
	Semver        string `protobuf:"bytes,3,opt,name=semver,proto3" json:"semver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LunarClientVersion) Reset() {
	*x = LunarClientVersion{}
	mi := &file_lunarclient_apollo_common_v1_version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LunarClientVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LunarClientVersion) ProtoMessage() {}

func (x *LunarClientVersion) ProtoReflect() protoreflect.Message {
	mi := &file_lunarclient_apollo_common_v1_version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LunarClientVersion.ProtoReflect.Descriptor instead.
func (*LunarClientVersion) Descriptor() ([]byte, []int) {
	return file_lunarclient_apollo_common_v1_version_proto_rawDescGZIP(), []int{1}
}

func (x *LunarClientVersion) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *LunarClientVersion) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *LunarClientVersion) GetSemver() string {
	if x != nil {
		return x.Semver
	}
	return ""
}

var File_lunarclient_apollo_common_v1_version_proto protoreflect.FileDescriptor

const file_lunarclient_apollo_common_v1_version_proto_rawDesc = "" +
	"\n" +
	"*lunarclient/apollo/common/v1/version.proto\x12\x1clunarclient.apollo.common.v1\"&\n" +
	"\x10MinecraftVersion\x12\x12\n" +
	"\x04enum\x18\x01 \x01(\tR\x04enum\"j\n" +
	"\x12LunarClientVersion\x12\x1d\n" +
	"\n" +
	"git_branch\x18\x01 \x01(\tR\tgitBranch\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x02 \x01(\tR\tgitCommit\x12\x16\n" +
	"\x06semver\x18\x03 \x01(\tR\x06semverBbZ`github.com/minekube/gate-plugin-template/plugins/detection/lunar_pb/lunarclient/apollo/common/v1b\x06proto3"

var (
	file_lunarclient_apollo_common_v1_version_proto_rawDescOnce sync.Once
	file_lunarclient_apollo_common_v1_version_proto_rawDescData []byte
)

func file_lunarclient_apollo_common_v1_version_proto_rawDescGZIP() []byte {
	file_lunarclient_apollo_common_v1_version_proto_rawDescOnce.Do(func() {
		file_lunarclient_apollo_common_v1_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lunarclient_apollo_common_v1_version_proto_rawDesc), len(file_lunarclient_apollo_common_v1_version_proto_rawDesc)))
	})
	return file_lunarclient_apollo_common_v1_version_proto_rawDescData
}

var file_lunarclient_apollo_common_v1_version_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lunarclient_apollo_common_v1_version_proto_goTypes = []any{
	(*MinecraftVersion)(nil),   // 0: lunarclient.apollo.common.v1.MinecraftVersion
	(*LunarClientVersion)(nil), // 1: lunarclient.apollo.common.v1.LunarClientVersion
}
var file_lunarclient_apollo_common_v1_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lunarclient_apollo_common_v1_version_proto_init() }
func file_lunarclient_apollo_common_v1_version_proto_init() {
	if File_lunarclient_apollo_common_v1_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lunarclient_apollo_common_v1_version_proto_rawDesc), len(file_lunarclient_apollo_common_v1_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lunarclient_apollo_common_v1_version_proto_goTypes,
		DependencyIndexes: file_lunarclient_apollo_common_v1_version_proto_depIdxs,
		MessageInfos:      file_lunarclient_apollo_common_v1_version_proto_msgTypes,
	}.Build()
	File_lunarclient_apollo_common_v1_version_proto = out.File
	file_lunarclient_apollo_common_v1_version_proto_goTypes = nil
	file_lunarclient_apollo_common_v1_version_proto_depIdxs = nil
}
