// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: lunarclient/apollo/player/v1/handshake.proto

package v1

import (
	v1 "github.com/minekube/gate-plugin-template/plugins/detection/lunar_pb/lunarclient/apollo/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbeddedCheckoutSupport int32

const (
	EmbeddedCheckoutSupport_EMBEDDED_CHECKOUT_SUPPORT_UNSPECIFIED EmbeddedCheckoutSupport = 0
	// External checkout is supported as a game overlay
	EmbeddedCheckoutSupport_EMBEDDED_CHECKOUT_SUPPORT_OVERLAY EmbeddedCheckoutSupport = 1
	// Embedded checkout is supported in an external window
	EmbeddedCheckoutSupport_EMBEDDED_CHECKOUT_SUPPORT_WINDOW EmbeddedCheckoutSupport = 2
)

// Enum value maps for EmbeddedCheckoutSupport.
var (
	EmbeddedCheckoutSupport_name = map[int32]string{
		0: "EMBEDDED_CHECKOUT_SUPPORT_UNSPECIFIED",
		1: "EMBEDDED_CHECKOUT_SUPPORT_OVERLAY",
		2: "EMBEDDED_CHECKOUT_SUPPORT_WINDOW",
	}
	EmbeddedCheckoutSupport_value = map[string]int32{
		"EMBEDDED_CHECKOUT_SUPPORT_UNSPECIFIED": 0,
		"EMBEDDED_CHECKOUT_SUPPORT_OVERLAY":     1,
		"EMBEDDED_CHECKOUT_SUPPORT_WINDOW":      2,
	}
)

func (x EmbeddedCheckoutSupport) Enum() *EmbeddedCheckoutSupport {
	p := new(EmbeddedCheckoutSupport)
	*p = x
	return p
}

func (x EmbeddedCheckoutSupport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmbeddedCheckoutSupport) Descriptor() protoreflect.EnumDescriptor {
	return file_lunarclient_apollo_player_v1_handshake_proto_enumTypes[0].Descriptor()
}

func (EmbeddedCheckoutSupport) Type() protoreflect.EnumType {
	return &file_lunarclient_apollo_player_v1_handshake_proto_enumTypes[0]
}

func (x EmbeddedCheckoutSupport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmbeddedCheckoutSupport.Descriptor instead.
func (EmbeddedCheckoutSupport) EnumDescriptor() ([]byte, []int) {
	return file_lunarclient_apollo_player_v1_handshake_proto_rawDescGZIP(), []int{0}
}

type ModMessage_Type int32

const (
	ModMessage_TYPE_UNSPECIFIED ModMessage_Type = 0
	// Internal (shipped in Lunar) Fabric-based mod
	ModMessage_TYPE_FABRIC_INTERNAL ModMessage_Type = 1
	// External (loaded from mods folder) Fabric-based mod
	ModMessage_TYPE_FABRIC_EXTERNAL ModMessage_Type = 2
	// Internal (shipped in Lunar) Forge-based mod
	ModMessage_TYPE_FORGE_INTERNAL ModMessage_Type = 3
	// External (loaded from mods folder) Forge-based mod
	ModMessage_TYPE_FORGE_EXTERNAL ModMessage_Type = 4
)

// Enum value maps for ModMessage_Type.
var (
	ModMessage_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_FABRIC_INTERNAL",
		2: "TYPE_FABRIC_EXTERNAL",
		3: "TYPE_FORGE_INTERNAL",
		4: "TYPE_FORGE_EXTERNAL",
	}
	ModMessage_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":     0,
		"TYPE_FABRIC_INTERNAL": 1,
		"TYPE_FABRIC_EXTERNAL": 2,
		"TYPE_FORGE_INTERNAL":  3,
		"TYPE_FORGE_EXTERNAL":  4,
	}
)

func (x ModMessage_Type) Enum() *ModMessage_Type {
	p := new(ModMessage_Type)
	*p = x
	return p
}

func (x ModMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_lunarclient_apollo_player_v1_handshake_proto_enumTypes[1].Descriptor()
}

func (ModMessage_Type) Type() protoreflect.EnumType {
	return &file_lunarclient_apollo_player_v1_handshake_proto_enumTypes[1]
}

func (x ModMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModMessage_Type.Descriptor instead.
func (ModMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_lunarclient_apollo_player_v1_handshake_proto_rawDescGZIP(), []int{0, 0}
}

type ModMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID (ex: `sodium`) of this mod. Exact meaning varies based on the loader
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name (ex: `Sodium`) of this mod.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version (ex: `1.2.21`) of this mod.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// The type of mod this is
	Type          ModMessage_Type `protobuf:"varint,4,opt,name=type,proto3,enum=lunarclient.apollo.player.v1.ModMessage_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModMessage) Reset() {
	*x = ModMessage{}
	mi := &file_lunarclient_apollo_player_v1_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModMessage) ProtoMessage() {}

func (x *ModMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lunarclient_apollo_player_v1_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModMessage.ProtoReflect.Descriptor instead.
func (*ModMessage) Descriptor() ([]byte, []int) {
	return file_lunarclient_apollo_player_v1_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *ModMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModMessage) GetType() ModMessage_Type {
	if x != nil {
		return x.Type
	}
	return ModMessage_TYPE_UNSPECIFIED
}

type PlayerHandshakeMessage struct {
	state                   protoimpl.MessageState     `protogen:"open.v1"`
	MinecraftVersion        *v1.MinecraftVersion       `protobuf:"bytes,1,opt,name=minecraft_version,json=minecraftVersion,proto3" json:"minecraft_version,omitempty"`
	LunarClientVersion      *v1.LunarClientVersion     `protobuf:"bytes,2,opt,name=lunar_client_version,json=lunarClientVersion,proto3" json:"lunar_client_version,omitempty"`
	InstalledMods           []*ModMessage              `protobuf:"bytes,3,rep,name=installed_mods,json=installedMods,proto3" json:"installed_mods,omitempty"`
	EmbeddedCheckoutSupport EmbeddedCheckoutSupport    `protobuf:"varint,4,opt,name=embedded_checkout_support,json=embeddedCheckoutSupport,proto3,enum=lunarclient.apollo.player.v1.EmbeddedCheckoutSupport" json:"embedded_checkout_support,omitempty"`
	ModStatus               map[string]*structpb.Value `protobuf:"bytes,5,rep,name=mod_status,json=modStatus,proto3" json:"mod_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PlayerHandshakeMessage) Reset() {
	*x = PlayerHandshakeMessage{}
	mi := &file_lunarclient_apollo_player_v1_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerHandshakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerHandshakeMessage) ProtoMessage() {}

func (x *PlayerHandshakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lunarclient_apollo_player_v1_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerHandshakeMessage.ProtoReflect.Descriptor instead.
func (*PlayerHandshakeMessage) Descriptor() ([]byte, []int) {
	return file_lunarclient_apollo_player_v1_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerHandshakeMessage) GetMinecraftVersion() *v1.MinecraftVersion {
	if x != nil {
		return x.MinecraftVersion
	}
	return nil
}

func (x *PlayerHandshakeMessage) GetLunarClientVersion() *v1.LunarClientVersion {
	if x != nil {
		return x.LunarClientVersion
	}
	return nil
}

func (x *PlayerHandshakeMessage) GetInstalledMods() []*ModMessage {
	if x != nil {
		return x.InstalledMods
	}
	return nil
}

func (x *PlayerHandshakeMessage) GetEmbeddedCheckoutSupport() EmbeddedCheckoutSupport {
	if x != nil {
		return x.EmbeddedCheckoutSupport
	}
	return EmbeddedCheckoutSupport_EMBEDDED_CHECKOUT_SUPPORT_UNSPECIFIED
}

func (x *PlayerHandshakeMessage) GetModStatus() map[string]*structpb.Value {
	if x != nil {
		return x.ModStatus
	}
	return nil
}

var File_lunarclient_apollo_player_v1_handshake_proto protoreflect.FileDescriptor

const file_lunarclient_apollo_player_v1_handshake_proto_rawDesc = "" +
	"\n" +
	",lunarclient/apollo/player/v1/handshake.proto\x12\x1clunarclient.apollo.player.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a*lunarclient/apollo/common/v1/version.proto\"\x92\x02\n" +
	"\n" +
	"ModMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12A\n" +
	"\x04type\x18\x04 \x01(\x0e2-.lunarclient.apollo.player.v1.ModMessage.TypeR\x04type\"\x82\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TYPE_FABRIC_INTERNAL\x10\x01\x12\x18\n" +
	"\x14TYPE_FABRIC_EXTERNAL\x10\x02\x12\x17\n" +
	"\x13TYPE_FORGE_INTERNAL\x10\x03\x12\x17\n" +
	"\x13TYPE_FORGE_EXTERNAL\x10\x04\"\xd7\x04\n" +
	"\x16PlayerHandshakeMessage\x12[\n" +
	"\x11minecraft_version\x18\x01 \x01(\v2..lunarclient.apollo.common.v1.MinecraftVersionR\x10minecraftVersion\x12b\n" +
	"\x14lunar_client_version\x18\x02 \x01(\v20.lunarclient.apollo.common.v1.LunarClientVersionR\x12lunarClientVersion\x12O\n" +
	"\x0einstalled_mods\x18\x03 \x03(\v2(.lunarclient.apollo.player.v1.ModMessageR\rinstalledMods\x12q\n" +
	"\x19embedded_checkout_support\x18\x04 \x01(\x0e25.lunarclient.apollo.player.v1.EmbeddedCheckoutSupportR\x17embeddedCheckoutSupport\x12b\n" +
	"\n" +
	"mod_status\x18\x05 \x03(\v2C.lunarclient.apollo.player.v1.PlayerHandshakeMessage.ModStatusEntryR\tmodStatus\x1aT\n" +
	"\x0eModStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01*\x91\x01\n" +
	"\x17EmbeddedCheckoutSupport\x12)\n" +
	"%EMBEDDED_CHECKOUT_SUPPORT_UNSPECIFIED\x10\x00\x12%\n" +
	"!EMBEDDED_CHECKOUT_SUPPORT_OVERLAY\x10\x01\x12$\n" +
	" EMBEDDED_CHECKOUT_SUPPORT_WINDOW\x10\x02BbZ`github.com/minekube/gate-plugin-template/plugins/detection/lunar_pb/lunarclient/apollo/player/v1b\x06proto3"

var (
	file_lunarclient_apollo_player_v1_handshake_proto_rawDescOnce sync.Once
	file_lunarclient_apollo_player_v1_handshake_proto_rawDescData []byte
)

func file_lunarclient_apollo_player_v1_handshake_proto_rawDescGZIP() []byte {
	file_lunarclient_apollo_player_v1_handshake_proto_rawDescOnce.Do(func() {
		file_lunarclient_apollo_player_v1_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lunarclient_apollo_player_v1_handshake_proto_rawDesc), len(file_lunarclient_apollo_player_v1_handshake_proto_rawDesc)))
	})
	return file_lunarclient_apollo_player_v1_handshake_proto_rawDescData
}

var file_lunarclient_apollo_player_v1_handshake_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_lunarclient_apollo_player_v1_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lunarclient_apollo_player_v1_handshake_proto_goTypes = []any{
	(EmbeddedCheckoutSupport)(0),   // 0: lunarclient.apollo.player.v1.EmbeddedCheckoutSupport
	(ModMessage_Type)(0),           // 1: lunarclient.apollo.player.v1.ModMessage.Type
	(*ModMessage)(nil),             // 2: lunarclient.apollo.player.v1.ModMessage
	(*PlayerHandshakeMessage)(nil), // 3: lunarclient.apollo.player.v1.PlayerHandshakeMessage
	nil,                            // 4: lunarclient.apollo.player.v1.PlayerHandshakeMessage.ModStatusEntry
	(*v1.MinecraftVersion)(nil),    // 5: lunarclient.apollo.common.v1.MinecraftVersion
	(*v1.LunarClientVersion)(nil),  // 6: lunarclient.apollo.common.v1.LunarClientVersion
	(*structpb.Value)(nil),         // 7: google.protobuf.Value
}
var file_lunarclient_apollo_player_v1_handshake_proto_depIdxs = []int32{
	1, // 0: lunarclient.apollo.player.v1.ModMessage.type:type_name -> lunarclient.apollo.player.v1.ModMessage.Type
	5, // 1: lunarclient.apollo.player.v1.PlayerHandshakeMessage.minecraft_version:type_name -> lunarclient.apollo.common.v1.MinecraftVersion
	6, // 2: lunarclient.apollo.player.v1.PlayerHandshakeMessage.lunar_client_version:type_name -> lunarclient.apollo.common.v1.LunarClientVersion
	2, // 3: lunarclient.apollo.player.v1.PlayerHandshakeMessage.installed_mods:type_name -> lunarclient.apollo.player.v1.ModMessage
	0, // 4: lunarclient.apollo.player.v1.PlayerHandshakeMessage.embedded_checkout_support:type_name -> lunarclient.apollo.player.v1.EmbeddedCheckoutSupport
	4, // 5: lunarclient.apollo.player.v1.PlayerHandshakeMessage.mod_status:type_name -> lunarclient.apollo.player.v1.PlayerHandshakeMessage.ModStatusEntry
	7, // 6: lunarclient.apollo.player.v1.PlayerHandshakeMessage.ModStatusEntry.value:type_name -> google.protobuf.Value
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_lunarclient_apollo_player_v1_handshake_proto_init() }
func file_lunarclient_apollo_player_v1_handshake_proto_init() {
	if File_lunarclient_apollo_player_v1_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lunarclient_apollo_player_v1_handshake_proto_rawDesc), len(file_lunarclient_apollo_player_v1_handshake_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lunarclient_apollo_player_v1_handshake_proto_goTypes,
		DependencyIndexes: file_lunarclient_apollo_player_v1_handshake_proto_depIdxs,
		EnumInfos:         file_lunarclient_apollo_player_v1_handshake_proto_enumTypes,
		MessageInfos:      file_lunarclient_apollo_player_v1_handshake_proto_msgTypes,
	}.Build()
	File_lunarclient_apollo_player_v1_handshake_proto = out.File
	file_lunarclient_apollo_player_v1_handshake_proto_goTypes = nil
	file_lunarclient_apollo_player_v1_handshake_proto_depIdxs = nil
}
